[prometheus_agents]
vm1 ansible_host=20.16.198.44
vm2 ansible_host=20.16.198.73

[all:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=./key.pem
ansible_python_interpreter=/usr/bin/python3.10